Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/test_helper.rb'
    - 'Guardfile'

